// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package server

import (
	"context"

	"iot-platform/app/product/rpc/internal/logic"
	"iot-platform/app/product/rpc/internal/svc"
	"iot-platform/app/product/rpc/types/product"
)

type ProductSvcServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductSvcServer
}

func NewProductSvcServer(svcCtx *svc.ServiceContext) *ProductSvcServer {
	return &ProductSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductSvcServer) CreateProduct(ctx context.Context, in *product.CreateProductReq) (*product.CreateProductResp, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductSvcServer) UpdateProduct(ctx context.Context, in *product.UpdateProductReq) (*product.UpdateProductResp, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

func (s *ProductSvcServer) DeleteProduct(ctx context.Context, in *product.DeleteProductReq) (*product.DeleteProductResp, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

func (s *ProductSvcServer) GetProductList(ctx context.Context, in *product.ProductListReq) (*product.ProductListResp, error) {
	l := logic.NewGetProductListLogic(ctx, s.svcCtx)
	return l.GetProductList(in)
}
