// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: device.proto

package server

import (
	"context"

	"iot-platform/app/device/rpc/internal/logic"
	"iot-platform/app/device/rpc/internal/svc"
	"iot-platform/app/device/rpc/types/device"
)

type DeviceSvcServer struct {
	svcCtx *svc.ServiceContext
	device.UnimplementedDeviceSvcServer
}

func NewDeviceSvcServer(svcCtx *svc.ServiceContext) *DeviceSvcServer {
	return &DeviceSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *DeviceSvcServer) DeviceList(ctx context.Context, in *device.DeviceListReq) (*device.DeviceListResp, error) {
	l := logic.NewDeviceListLogic(ctx, s.svcCtx)
	return l.DeviceList(in)
}

func (s *DeviceSvcServer) DeviceCreate(ctx context.Context, in *device.DeviceCreateReq) (*device.DeviceCreateResp, error) {
	l := logic.NewDeviceCreateLogic(ctx, s.svcCtx)
	return l.DeviceCreate(in)
}

func (s *DeviceSvcServer) DeviceUpdate(ctx context.Context, in *device.DeviceUpdateReq) (*device.DeviceUpdateResp, error) {
	l := logic.NewDeviceUpdateLogic(ctx, s.svcCtx)
	return l.DeviceUpdate(in)
}

func (s *DeviceSvcServer) DeviceDelete(ctx context.Context, in *device.DeviceDeleteReq) (*device.DeviceDeleteResp, error) {
	l := logic.NewDeviceDeleteLogic(ctx, s.svcCtx)
	return l.DeviceDelete(in)
}

func (s *DeviceSvcServer) SendMessageToDevice(ctx context.Context, in *device.SendMessageToDeviceReq) (*device.Empty, error) {
	l := logic.NewSendMessageToDeviceLogic(ctx, s.svcCtx)
	return l.SendMessageToDevice(in)
}
