// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: product.proto

package productsvc

import (
	"context"

	"iot-platform/app/product/rpc/types/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateProductReq  = product.CreateProductReq
	CreateProductResp = product.CreateProductResp
	DeleteProductReq  = product.DeleteProductReq
	DeleteProductResp = product.DeleteProductResp
	Product           = product.Product
	ProductListReq    = product.ProductListReq
	ProductListResp   = product.ProductListResp
	UpdateProductReq  = product.UpdateProductReq
	UpdateProductResp = product.UpdateProductResp

	ProductSvc interface {
		CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error)
		UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error)
		DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error)
		GetProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error)
	}

	defaultProductSvc struct {
		cli zrpc.Client
	}
)

func NewProductSvc(cli zrpc.Client) ProductSvc {
	return &defaultProductSvc{
		cli: cli,
	}
}

func (m *defaultProductSvc) CreateProduct(ctx context.Context, in *CreateProductReq, opts ...grpc.CallOption) (*CreateProductResp, error) {
	client := product.NewProductSvcClient(m.cli.Conn())
	return client.CreateProduct(ctx, in, opts...)
}

func (m *defaultProductSvc) UpdateProduct(ctx context.Context, in *UpdateProductReq, opts ...grpc.CallOption) (*UpdateProductResp, error) {
	client := product.NewProductSvcClient(m.cli.Conn())
	return client.UpdateProduct(ctx, in, opts...)
}

func (m *defaultProductSvc) DeleteProduct(ctx context.Context, in *DeleteProductReq, opts ...grpc.CallOption) (*DeleteProductResp, error) {
	client := product.NewProductSvcClient(m.cli.Conn())
	return client.DeleteProduct(ctx, in, opts...)
}

func (m *defaultProductSvc) GetProductList(ctx context.Context, in *ProductListReq, opts ...grpc.CallOption) (*ProductListResp, error) {
	client := product.NewProductSvcClient(m.cli.Conn())
	return client.GetProductList(ctx, in, opts...)
}
