// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"iot-platform/app/openapi/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/openapi/device/send",
					Handler: sendMsgHandler(serverCtx),
				},
			}...,
		),
	)
}
