// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateProductReq struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateProductResp struct {
	Success   bool   `json:"success"`
	ProductId int64  `json:"product_id"`
	Msg       string `json:"msg"`
}

type DeleteProductReq struct {
	Id int64 `path:"id"`
}

type DeleteProductResp struct {
	Success bool   `json:"success"`
	Msg     string `json:"msg"`
}

type Product struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type ProductListReq struct {
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
	Name     string `form:"name,optional"`
}

type ProductListResp struct {
	Success bool      `json:"success"`
	Total   int64     `json:"total"`
	List    []Product `json:"list"`
	Msg     string    `json:"msg"`
}

type UpdateProductReq struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type UpdateProductResp struct {
	Success bool   `json:"success"`
	Msg     string `json:"msg"`
}
