// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: device.proto

package devicesvc

import (
	"context"

	"iot-platform/app/device/rpc/types/device"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DeviceCreateReq        = device.DeviceCreateReq
	DeviceCreateResp       = device.DeviceCreateResp
	DeviceDeleteReq        = device.DeviceDeleteReq
	DeviceDeleteResp       = device.DeviceDeleteResp
	DeviceInfo             = device.DeviceInfo
	DeviceListReq          = device.DeviceListReq
	DeviceListResp         = device.DeviceListResp
	DeviceUpdateReq        = device.DeviceUpdateReq
	DeviceUpdateResp       = device.DeviceUpdateResp
	Empty                  = device.Empty
	SendMessageToDeviceReq = device.SendMessageToDeviceReq

	DeviceSvc interface {
		DeviceList(ctx context.Context, in *DeviceListReq, opts ...grpc.CallOption) (*DeviceListResp, error)
		DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateResp, error)
		DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateResp, error)
		DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteResp, error)
		SendMessageToDevice(ctx context.Context, in *SendMessageToDeviceReq, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultDeviceSvc struct {
		cli zrpc.Client
	}
)

func NewDeviceSvc(cli zrpc.Client) DeviceSvc {
	return &defaultDeviceSvc{
		cli: cli,
	}
}

func (m *defaultDeviceSvc) DeviceList(ctx context.Context, in *DeviceListReq, opts ...grpc.CallOption) (*DeviceListResp, error) {
	client := device.NewDeviceSvcClient(m.cli.Conn())
	return client.DeviceList(ctx, in, opts...)
}

func (m *defaultDeviceSvc) DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateResp, error) {
	client := device.NewDeviceSvcClient(m.cli.Conn())
	return client.DeviceCreate(ctx, in, opts...)
}

func (m *defaultDeviceSvc) DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateResp, error) {
	client := device.NewDeviceSvcClient(m.cli.Conn())
	return client.DeviceUpdate(ctx, in, opts...)
}

func (m *defaultDeviceSvc) DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteResp, error) {
	client := device.NewDeviceSvcClient(m.cli.Conn())
	return client.DeviceDelete(ctx, in, opts...)
}

func (m *defaultDeviceSvc) SendMessageToDevice(ctx context.Context, in *SendMessageToDeviceReq, opts ...grpc.CallOption) (*Empty, error) {
	client := device.NewDeviceSvcClient(m.cli.Conn())
	return client.SendMessageToDevice(ctx, in, opts...)
}
