// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId      int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DeviceKey      string                 `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Status         int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	LastOnlineTime string                 `protobuf:"bytes,6,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceInfo) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *DeviceInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeviceInfo) GetLastOnlineTime() string {
	if x != nil {
		return x.LastOnlineTime
	}
	return ""
}

func (x *DeviceInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DeviceInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeviceListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Keyword       string                 `protobuf:"bytes,5,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceListReq) Reset() {
	*x = DeviceListReq{}
	mi := &file_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceListReq) ProtoMessage() {}

func (x *DeviceListReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceListReq.ProtoReflect.Descriptor instead.
func (*DeviceListReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DeviceListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DeviceListReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeviceListReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeviceListReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type DeviceListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*DeviceInfo          `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceListResp) Reset() {
	*x = DeviceListResp{}
	mi := &file_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceListResp) ProtoMessage() {}

func (x *DeviceListResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceListResp.ProtoReflect.Descriptor instead.
func (*DeviceListResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeviceListResp) GetList() []*DeviceInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type DeviceCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DeviceKey     string                 `protobuf:"bytes,3,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCreateReq) Reset() {
	*x = DeviceCreateReq{}
	mi := &file_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreateReq) ProtoMessage() {}

func (x *DeviceCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreateReq.ProtoReflect.Descriptor instead.
func (*DeviceCreateReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceCreateReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeviceCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceCreateReq) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *DeviceCreateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeviceCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceCreateResp) Reset() {
	*x = DeviceCreateResp{}
	mi := &file_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreateResp) ProtoMessage() {}

func (x *DeviceCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreateResp.ProtoReflect.Descriptor instead.
func (*DeviceCreateResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceCreateResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeviceUpdateReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId      int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DeviceKey      string                 `protobuf:"bytes,4,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Status         int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	LastOnlineTime string                 `protobuf:"bytes,6,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeviceUpdateReq) Reset() {
	*x = DeviceUpdateReq{}
	mi := &file_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUpdateReq) ProtoMessage() {}

func (x *DeviceUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUpdateReq.ProtoReflect.Descriptor instead.
func (*DeviceUpdateReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceUpdateReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceUpdateReq) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *DeviceUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceUpdateReq) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *DeviceUpdateReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DeviceUpdateReq) GetLastOnlineTime() string {
	if x != nil {
		return x.LastOnlineTime
	}
	return ""
}

type DeviceUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceUpdateResp) Reset() {
	*x = DeviceUpdateResp{}
	mi := &file_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceUpdateResp) ProtoMessage() {}

func (x *DeviceUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceUpdateResp.ProtoReflect.Descriptor instead.
func (*DeviceUpdateResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceUpdateResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeviceDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDeleteReq) Reset() {
	*x = DeviceDeleteReq{}
	mi := &file_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDeleteReq) ProtoMessage() {}

func (x *DeviceDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDeleteReq.ProtoReflect.Descriptor instead.
func (*DeviceDeleteReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceDeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeviceDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDeleteResp) Reset() {
	*x = DeviceDeleteResp{}
	mi := &file_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDeleteResp) ProtoMessage() {}

func (x *DeviceDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDeleteResp.ProtoReflect.Descriptor instead.
func (*DeviceDeleteResp) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceDeleteResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{9}
}

type SendMessageToDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceKey     string                 `protobuf:"bytes,1,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToDeviceReq) Reset() {
	*x = SendMessageToDeviceReq{}
	mi := &file_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToDeviceReq) ProtoMessage() {}

func (x *SendMessageToDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToDeviceReq.ProtoReflect.Descriptor instead.
func (*SendMessageToDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageToDeviceReq) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *SendMessageToDeviceReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_device_proto protoreflect.FileDescriptor

const file_device_proto_rawDesc = "" +
	"\n" +
	"\fdevice.proto\x12\x06device\"\xee\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"device_key\x18\x04 \x01(\tR\tdeviceKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12(\n" +
	"\x10last_online_time\x18\x06 \x01(\tR\x0elastOnlineTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x91\x01\n" +
	"\rDeviceListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x03R\bpageSize\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x18\n" +
	"\akeyword\x18\x05 \x01(\tR\akeyword\"N\n" +
	"\x0eDeviceListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x04list\x18\x02 \x03(\v2\x12.device.DeviceInfoR\x04list\"{\n" +
	"\x0fDeviceCreateReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"device_key\x18\x03 \x01(\tR\tdeviceKey\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\"\n" +
	"\x10DeviceCreateResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb5\x01\n" +
	"\x0fDeviceUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"device_key\x18\x04 \x01(\tR\tdeviceKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12(\n" +
	"\x10last_online_time\x18\x06 \x01(\tR\x0elastOnlineTime\",\n" +
	"\x10DeviceUpdateResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x0fDeviceDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x10DeviceDeleteResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\a\n" +
	"\x05Empty\"Q\n" +
	"\x16SendMessageToDeviceReq\x12\x1d\n" +
	"\n" +
	"device_key\x18\x01 \x01(\tR\tdeviceKey\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2\xd7\x02\n" +
	"\tDeviceSvc\x12;\n" +
	"\n" +
	"deviceList\x12\x15.device.DeviceListReq\x1a\x16.device.DeviceListResp\x12A\n" +
	"\fdeviceCreate\x12\x17.device.DeviceCreateReq\x1a\x18.device.DeviceCreateResp\x12A\n" +
	"\fdeviceUpdate\x12\x17.device.DeviceUpdateReq\x1a\x18.device.DeviceUpdateResp\x12A\n" +
	"\fdeviceDelete\x12\x17.device.DeviceDeleteReq\x1a\x18.device.DeviceDeleteResp\x12D\n" +
	"\x13sendMessageToDevice\x12\x1e.device.SendMessageToDeviceReq\x1a\r.device.EmptyB\n" +
	"Z\b./deviceb\x06proto3"

var (
	file_device_proto_rawDescOnce sync.Once
	file_device_proto_rawDescData []byte
)

func file_device_proto_rawDescGZIP() []byte {
	file_device_proto_rawDescOnce.Do(func() {
		file_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)))
	})
	return file_device_proto_rawDescData
}

var file_device_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_device_proto_goTypes = []any{
	(*DeviceInfo)(nil),             // 0: device.DeviceInfo
	(*DeviceListReq)(nil),          // 1: device.DeviceListReq
	(*DeviceListResp)(nil),         // 2: device.DeviceListResp
	(*DeviceCreateReq)(nil),        // 3: device.DeviceCreateReq
	(*DeviceCreateResp)(nil),       // 4: device.DeviceCreateResp
	(*DeviceUpdateReq)(nil),        // 5: device.DeviceUpdateReq
	(*DeviceUpdateResp)(nil),       // 6: device.DeviceUpdateResp
	(*DeviceDeleteReq)(nil),        // 7: device.DeviceDeleteReq
	(*DeviceDeleteResp)(nil),       // 8: device.DeviceDeleteResp
	(*Empty)(nil),                  // 9: device.Empty
	(*SendMessageToDeviceReq)(nil), // 10: device.SendMessageToDeviceReq
}
var file_device_proto_depIdxs = []int32{
	0,  // 0: device.DeviceListResp.list:type_name -> device.DeviceInfo
	1,  // 1: device.DeviceSvc.deviceList:input_type -> device.DeviceListReq
	3,  // 2: device.DeviceSvc.deviceCreate:input_type -> device.DeviceCreateReq
	5,  // 3: device.DeviceSvc.deviceUpdate:input_type -> device.DeviceUpdateReq
	7,  // 4: device.DeviceSvc.deviceDelete:input_type -> device.DeviceDeleteReq
	10, // 5: device.DeviceSvc.sendMessageToDevice:input_type -> device.SendMessageToDeviceReq
	2,  // 6: device.DeviceSvc.deviceList:output_type -> device.DeviceListResp
	4,  // 7: device.DeviceSvc.deviceCreate:output_type -> device.DeviceCreateResp
	6,  // 8: device.DeviceSvc.deviceUpdate:output_type -> device.DeviceUpdateResp
	8,  // 9: device.DeviceSvc.deviceDelete:output_type -> device.DeviceDeleteResp
	9,  // 10: device.DeviceSvc.sendMessageToDevice:output_type -> device.Empty
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_device_proto_init() }
func file_device_proto_init() {
	if File_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_proto_rawDesc), len(file_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_proto_goTypes,
		DependencyIndexes: file_device_proto_depIdxs,
		MessageInfos:      file_device_proto_msgTypes,
	}.Build()
	File_device_proto = out.File
	file_device_proto_goTypes = nil
	file_device_proto_depIdxs = nil
}
