// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: device.proto

package device

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceSvc_DeviceList_FullMethodName          = "/device.DeviceSvc/deviceList"
	DeviceSvc_DeviceCreate_FullMethodName        = "/device.DeviceSvc/deviceCreate"
	DeviceSvc_DeviceUpdate_FullMethodName        = "/device.DeviceSvc/deviceUpdate"
	DeviceSvc_DeviceDelete_FullMethodName        = "/device.DeviceSvc/deviceDelete"
	DeviceSvc_SendMessageToDevice_FullMethodName = "/device.DeviceSvc/sendMessageToDevice"
)

// DeviceSvcClient is the client API for DeviceSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceSvcClient interface {
	DeviceList(ctx context.Context, in *DeviceListReq, opts ...grpc.CallOption) (*DeviceListResp, error)
	DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateResp, error)
	DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateResp, error)
	DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteResp, error)
	SendMessageToDevice(ctx context.Context, in *SendMessageToDeviceReq, opts ...grpc.CallOption) (*Empty, error)
}

type deviceSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceSvcClient(cc grpc.ClientConnInterface) DeviceSvcClient {
	return &deviceSvcClient{cc}
}

func (c *deviceSvcClient) DeviceList(ctx context.Context, in *DeviceListReq, opts ...grpc.CallOption) (*DeviceListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceListResp)
	err := c.cc.Invoke(ctx, DeviceSvc_DeviceList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceSvcClient) DeviceCreate(ctx context.Context, in *DeviceCreateReq, opts ...grpc.CallOption) (*DeviceCreateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceCreateResp)
	err := c.cc.Invoke(ctx, DeviceSvc_DeviceCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceSvcClient) DeviceUpdate(ctx context.Context, in *DeviceUpdateReq, opts ...grpc.CallOption) (*DeviceUpdateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceUpdateResp)
	err := c.cc.Invoke(ctx, DeviceSvc_DeviceUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceSvcClient) DeviceDelete(ctx context.Context, in *DeviceDeleteReq, opts ...grpc.CallOption) (*DeviceDeleteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceDeleteResp)
	err := c.cc.Invoke(ctx, DeviceSvc_DeviceDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceSvcClient) SendMessageToDevice(ctx context.Context, in *SendMessageToDeviceReq, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, DeviceSvc_SendMessageToDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceSvcServer is the server API for DeviceSvc service.
// All implementations must embed UnimplementedDeviceSvcServer
// for forward compatibility.
type DeviceSvcServer interface {
	DeviceList(context.Context, *DeviceListReq) (*DeviceListResp, error)
	DeviceCreate(context.Context, *DeviceCreateReq) (*DeviceCreateResp, error)
	DeviceUpdate(context.Context, *DeviceUpdateReq) (*DeviceUpdateResp, error)
	DeviceDelete(context.Context, *DeviceDeleteReq) (*DeviceDeleteResp, error)
	SendMessageToDevice(context.Context, *SendMessageToDeviceReq) (*Empty, error)
	mustEmbedUnimplementedDeviceSvcServer()
}

// UnimplementedDeviceSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceSvcServer struct{}

func (UnimplementedDeviceSvcServer) DeviceList(context.Context, *DeviceListReq) (*DeviceListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceList not implemented")
}
func (UnimplementedDeviceSvcServer) DeviceCreate(context.Context, *DeviceCreateReq) (*DeviceCreateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceCreate not implemented")
}
func (UnimplementedDeviceSvcServer) DeviceUpdate(context.Context, *DeviceUpdateReq) (*DeviceUpdateResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceUpdate not implemented")
}
func (UnimplementedDeviceSvcServer) DeviceDelete(context.Context, *DeviceDeleteReq) (*DeviceDeleteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeviceDelete not implemented")
}
func (UnimplementedDeviceSvcServer) SendMessageToDevice(context.Context, *SendMessageToDeviceReq) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessageToDevice not implemented")
}
func (UnimplementedDeviceSvcServer) mustEmbedUnimplementedDeviceSvcServer() {}
func (UnimplementedDeviceSvcServer) testEmbeddedByValue()                   {}

// UnsafeDeviceSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceSvcServer will
// result in compilation errors.
type UnsafeDeviceSvcServer interface {
	mustEmbedUnimplementedDeviceSvcServer()
}

func RegisterDeviceSvcServer(s grpc.ServiceRegistrar, srv DeviceSvcServer) {
	// If the following call panics, it indicates UnimplementedDeviceSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceSvc_ServiceDesc, srv)
}

func _DeviceSvc_DeviceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSvcServer).DeviceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSvc_DeviceList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSvcServer).DeviceList(ctx, req.(*DeviceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceSvc_DeviceCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceCreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSvcServer).DeviceCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSvc_DeviceCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSvcServer).DeviceCreate(ctx, req.(*DeviceCreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceSvc_DeviceUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSvcServer).DeviceUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSvc_DeviceUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSvcServer).DeviceUpdate(ctx, req.(*DeviceUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceSvc_DeviceDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSvcServer).DeviceDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSvc_DeviceDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSvcServer).DeviceDelete(ctx, req.(*DeviceDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceSvc_SendMessageToDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageToDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceSvcServer).SendMessageToDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceSvc_SendMessageToDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceSvcServer).SendMessageToDevice(ctx, req.(*SendMessageToDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceSvc_ServiceDesc is the grpc.ServiceDesc for DeviceSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "device.DeviceSvc",
	HandlerType: (*DeviceSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "deviceList",
			Handler:    _DeviceSvc_DeviceList_Handler,
		},
		{
			MethodName: "deviceCreate",
			Handler:    _DeviceSvc_DeviceCreate_Handler,
		},
		{
			MethodName: "deviceUpdate",
			Handler:    _DeviceSvc_DeviceUpdate_Handler,
		},
		{
			MethodName: "deviceDelete",
			Handler:    _DeviceSvc_DeviceDelete_Handler,
		},
		{
			MethodName: "sendMessageToDevice",
			Handler:    _DeviceSvc_SendMessageToDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "device.proto",
}
