// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type DeviceCreateReq struct {
	ProductId int64  `json:"product_id"`
	Name      string `json:"name"`
	DeviceKey string `json:"device_key"`
	Status    int32  `json:"status"`
}

type DeviceCreateResp struct {
	Id int64 `json:"id"`
}

type DeviceDeleteReq struct {
	Id int64 `path:"id"`
}

type DeviceDeleteResp struct {
	Success bool `json:"success"`
}

type DeviceItem struct {
	Id             int64  `json:"id"`
	ProductId      int64  `json:"product_id"`
	Name           string `json:"name"`
	DeviceKey      string `json:"device_key"`
	Status         int32  `json:"status"`
	LastOnlineTime string `json:"last_online_time"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}

type DeviceListReq struct {
	Page      int64  `form:"page"`
	PageSize  int64  `form:"page_size"`
	ProductId int64  `form:"product_id,optional"`
	Status    int32  `form:"status,optional"`
	Keyword   string `form:"keyword,optional"`
}

type DeviceListResp struct {
	Total int64        `json:"total"`
	List  []DeviceItem `json:"list"`
}

type DeviceUpdateReq struct {
	Id             int64  `json:"id"`
	ProductId      int64  `json:"product_id"`
	Name           string `json:"name"`
	DeviceKey      string `json:"device_key"`
	Status         int32  `json:"status"`
	LastOnlineTime string `json:"last_online_time,optional"`
}

type DeviceUpdateResp struct {
	Success bool `json:"success"`
}
