// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	deviceFieldNames          = builder.RawFieldNames(&Device{})
	deviceRows                = strings.Join(deviceFieldNames, ",")
	deviceRowsExpectAutoSet   = strings.Join(stringx.Remove(deviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	deviceRowsWithPlaceHolder = strings.Join(stringx.Remove(deviceFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	deviceModel interface {
		Insert(ctx context.Context, data *Device) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Device, error)
		FindOneByDeviceKey(ctx context.Context, deviceKey string) (*Device, error)
		Update(ctx context.Context, data *Device) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDeviceModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Device struct {
		Id             int64        `db:"id"`
		ProductId      int64        `db:"product_id"`
		Name           string       `db:"name"`
		DeviceKey      string       `db:"device_key"` // 设备唯一标识
		Status         int64        `db:"status"`     // 0:离线 1:在线
		LastOnlineTime sql.NullTime `db:"last_online_time"`
		CreatedAt      time.Time    `db:"created_at"`
		UpdatedAt      time.Time    `db:"updated_at"`
	}
)

func newDeviceModel(conn sqlx.SqlConn) *defaultDeviceModel {
	return &defaultDeviceModel{
		conn:  conn,
		table: "`device`",
	}
}

func (m *defaultDeviceModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDeviceModel) FindOne(ctx context.Context, id int64) (*Device, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", deviceRows, m.table)
	var resp Device
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) FindOneByDeviceKey(ctx context.Context, deviceKey string) (*Device, error) {
	var resp Device
	query := fmt.Sprintf("select %s from %s where `device_key` = ? limit 1", deviceRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, deviceKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDeviceModel) Insert(ctx context.Context, data *Device) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, deviceRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ProductId, data.Name, data.DeviceKey, data.Status, data.LastOnlineTime)
	return ret, err
}

func (m *defaultDeviceModel) Update(ctx context.Context, newData *Device) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, deviceRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.ProductId, newData.Name, newData.DeviceKey, newData.Status, newData.LastOnlineTime, newData.Id)
	return err
}

func (m *defaultDeviceModel) tableName() string {
	return m.table
}
