// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SendMsgReq struct {
	DeviceKey string `json:"device_key"`
	Payload   string `json:"payload"`
}

type SendMsgResp struct {
	Success bool   `json:"success"`
	Msg     string `json:"msg"`
}
